<template>
	<nav class="navbar navbar-collapse bg-body-tertiary border-bottom" :style="getStyle()">
		<div class="container-fluid">
			<a class="navbar-brand" href="#" @click.prevent="" aria-label="Tilbake til start">
				<img src="/images/Logo -lav.png" height="50px" v-if="status.statusId == 1" alt="Safe Haven">
				<img src="/images/Logo moderat.png" height="50px" v-if="status.statusId == 2" alt="Safe Haven">
				<img src="/images/Logo kritisk.png" height="50px" v-if="status.statusId == 3" alt="Safe Haven">
				<img src="/images/Logo uten status.png" height="50px" v-if="status.statusId == 0" alt="Safe Haven">
				<div></div>
			</a>
			<button class="navbar-toggler" style="border: none;" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<img v-if="easterEgg" src="/images/easterEggPerson.webp" height="50px" alt="Profil bilde">
				<img v-else src="/images/Asset 6.png" height="50px" alt="Profil bilde">
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<span></span>
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<!-- <li class="nav-item">
						<a class="nav-link" href="#/myProfile" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"><i class="fa-solid fa-user"></i> Min profil</a>
					</li> -->
					<!-- <li class="nav-item">
						<a class="nav-link" href="#" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"><i class="fa-solid fa-language"></i> Språk</a>
					</li> -->
					<li class="nav-item">
						<a class="nav-link" href="/Access/Logout"><i class="fa-solid fa-sign-out"></i> Logg ut</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";
import { SecureApiClient, Status } from "@/scripts/autogeneratedServices";

const status = ref<Status>(new Status({ statusId: 0, name: "Laster", description: "" }));
const easterEgg = ref(false);

onMounted(async () => {
	try {
		const api = new SecureApiClient("");

		if (await api.isEasterEggActivated()) {
			easterEgg.value = true;
		}

		const statusString = sessionStorage.getItem("topnav::status");
		if (statusString) {
			status.value = JSON.parse(statusString);
		}

		const statusNew = await api.getStatus();

		if (!statusString || status.value !== statusNew) {
			status.value = statusNew;
			sessionStorage.setItem("topnav::status", JSON.stringify(statusNew));
		}
	}
	catch (err) {
		console.error(err);
	}
});

function getStyle() {
	if(status.value.statusId === 1) {
		return "background-color: #E4F0D5 !important; border-color: #55821A !important;";
	}
	if(status.value.statusId === 2) {
		return "background-color: #FFF2E5 !important; border-color: #E69318 !important;";
	}
	if(status.value.statusId === 3) {
		return "background-color: #FFECEB !important; border-color: #B83232 !important;";
	}
	if(status.value.statusId === 0) {
		return "background-color: #EBF5FF !important; border-color: #387F93 !important;";
	}
}
</script>