<template>
	<nav class="navbar navbar-collapse bg-body-tertiary" data-bs-theme="dark">
		<div class="container-fluid">
			<a class="navbar-brand" href="#" @click.prevent="">
				<img src="/images/Logo -lav.png" height="50px">
			</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<img src="/images/Asset 6.png" height="50px">
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<span></span>
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item">
						<a class="nav-link" href="#" @click.prevent=""><i class="fa-solid fa-user"></i> Min profil</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/Access/Logout"><i class="fa-solid fa-sign-out"></i> Logg ut</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";
import { SecureApiClient } from "@/scripts/autogeneratedServices";

const status = ref(0);

onMounted(async () => {
	try {
		const api = new SecureApiClient("");
		status.value = 1;
		const statusString = sessionStorage.getItem("topnav::status");
		if (statusString) {
			status.value = JSON.parse(statusString);
		}

		// const statusId = await api.getStatusId();

		// if (!statusString || status.value !== statusId) {
		// 	status.value = statusId;
		// 	sessionStorage.setItem("topnav::status", JSON.stringify(statusId));
		// }
	}
	catch (err) {
		console.error(err);
	}

	// const statusString = sessionStorage.getItem("topnav::status");
	// status.value = statusString ? JSON.parse(statusString) : await api.getStatus();
	// if (!statusString) {
	// 	sessionStorage.setItem("topnav::status", JSON.stringify(status.value));
	// }
});
</script>