<template>
	<div class="container">
		<h1 class="text-center">VARSEL</h1>
		<div v-for="alert in alerts" :key="alert.text" class="alert" :class="alert.type">
			<div class="d-flex">
				<i class="fa-solid me-2 mt-1" :class="alert.icon"></i>
				<div>
					<div></div>
					<div>{{ alert.text }}</div>
				</div>
			</div>
		</div>
	</div>
</template>
<script lang="ts" setup>
import { onMounted, ref } from "vue";
import { SecureApiClient, Status } from "../autogeneratedServices";

const alerts = ref<{ date?:Date; text:string; type:string; icon:string; }[]>([]);

onMounted(async () => {
	const date = new Date();
	let status: Status = new Status({ statusId: 0, name: "Laster", description: "" });
	const statusString = sessionStorage.getItem("topnav::status");
	if (statusString) {
		status = JSON.parse(statusString);
	}
	
	if (status.statusId !== 1 && status.statusId !== 0) {
		alerts.value.push({
			date: date, 
			text: "Husk å feste alle løse gjenstander, ta en ekstra runde rundt eiendommen. I morgen fra klokken 16:00 ventes orkan med styrke på 40 m/s. Hvis du kan sette bilen på et trygt sted, anbefales dette. Hold deg innendørs!", 
			type: "alert-danger",
			icon: "fa-bell"
		});
	}
	
	if (status.statusId === 1 || status.statusId === 0) {
		const api = new SecureApiClient("");
		const myHome = await api.getHome();
		
		if (myHome.hasLackingItems && myHome.numberOfMissingTypes && myHome.numberOfMissingTypes > 1) {
			alerts.value.push({
				date: date, 
				text: "Din hustand mangler flere beredskapsartikler. Gå til mitt hjem for å se hvilke som trengs å fylles på.", 
				type: "alert-warning",
				icon: "fa-bell"
			});
		}
		
		myHome.items?.forEach(e => {
			const today = new Date();
			if (e.sellByDate && e.sellByDate < today) {
				alerts.value.push({
					date: date, 
					text: e.itemType?.name + " har gått ut på dato. På tide å bytte ut.", 
					type: "alert-warning",
					icon: "fa-trash"
				});
			}

			today.setDate(today.getDate() + 7);

			if (e.sellByDate && e.sellByDate < today && e.sellByDate > new Date()) {
				alerts.value.push({
					date: date, 
					text: e.itemType?.name + " går snart ut på dato ut på dato. På tide å bytte ut.", 
					type: "alert-info",
					icon: "fa-cookie-bite"
				});
			}
		});

		myHome.itemTypes?.forEach(e => {
			if (myHome.items && myHome.items.filter(e => e.itemTypeId === e.id).length < e.recomendedUnitPerPerson! * myHome.numberOfInhabitants!) {
				alerts.value.push({
					date: date, 
					text: "Din hustand har ikke registrert nok " + e.name + ". Vi anbefaler at din hustand har minst " + e.recomendedUnitPerPerson + " " + e.unit, 
					type: "alert-warning",
					icon: "fa-bell"
				});
			}
		});
	}

});


</script>

