<template>
	<div class="container mb-5">
		<h1 class="text-center">INFO</h1>
		<div class="d-flex justify-content-center mt-3">
			<div>
				<iframe src="https://www.youtube.com/embed/e75m35UZW3E?si=ZWfsv9WE8QCirihZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>
				</iframe>
				<div class="text-center"><small>Video: hjerte- og lungeredning</small></div>
			</div>
		</div>

		<div class="d-flex justify-content-center mt-5">
			<div>
				<iframe src="https://www.youtube.com/embed/lLkw4BXa7pQ?si=Ktj8JybjUmXEJMWU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>
				</iframe>
				<div class="text-center"><small>Video: Behandling av hoggormbitt (på engelsk)</small></div>
			</div>
		</div>

		<div class="d-flex justify-content-center mt-5">
			<div>
				<iframe src="https://www.youtube.com/embed/FwerEKvJjSA?si=7tjEonIKqUdC58MT" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>
				</iframe>
				<div class="text-center"><small>Video: Beredskap fra Røde Kors</small></div>
			</div>
		</div>
		<div class="d-flex justify-content-center mt-5">
			<div>
				<iframe src="https://www.youtube.com/embed/ZB6LIlCTrC4?si=aYj4dlQTpqZ4WYZp" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>
				</iframe>
				<div class="text-center"><small>Video: Stabilt sideleie</small></div>
			</div>
		</div>
		<div v-if="showChat" style="position: fixed; bottom: 0; right: 0; z-index: 100; margin-bottom: 165px; margin-right: 10px;">
			<div class="bg-white border rounded p-3" style="height: 500px; width: 300px;">
				<div class="overflow-auto" style="height: 430px;">
					<div v-for="chat in myChats" :key="chat.text" class="alert" :class="chat.isFromMe ? 'alert-light' : 'alert-info'">{{ chat.text }}</div>
				</div>
				<div class="d-flex">
					<input type="text" class="form-control" placeholder="Skriv spørsmål her" v-model="message" @keyup.enter="send()">
					<button type="button" class="btn btn-primary ms-2" @click="send()">
						<i class="fa-solid fa-paper-plane-top"></i>
					</button>
				</div>
			</div>
		</div>
		<div style="position: fixed; bottom: 0; right: 0; z-index: 100; margin-bottom: 100px; margin-right: 10px;">
			<button type="button" class="btn btn-primary btn-lg rounded-circle" aria-label="Chat" style="height: 60px; width: 60px;" @click="showChat = !showChat">
				<i class="fa-solid fa-robot"></i>
			</button>
		</div>
	</div>
</template>

<script lang="ts" setup>
import { ref } from "vue";
import { GptClient, GptEntity } from "../autogeneratedServices";

const showChat = ref(false);
const myChats = ref<{ text: string; isFromMe: boolean; }[]>([{ isFromMe: false, text: "Hei, jeg er chat gpt. Jeg kan svare på spørsmål om beredskap og førstehjelp. Det er viktig å huske at jeg bare er en robot og du bør alltid snakke med erfarne fagfolk først. Det er mer jeg ikke vet enn du tror." }]);
const message = ref("");

async function send() {
	const m = message.value + "";
	if (message.value === "") {
		return;
	}
	myChats.value.push({ isFromMe: true, text: message.value });
	message.value = "";

	try {
		const api = new GptClient("");
		const response = await api.generateResult(new GptEntity({ text: m }));
		myChats.value.push({ isFromMe: false, text: response });
	}
	catch (err) {
		myChats.value.push({ isFromMe: false, text: "Beklager, jeg fikk ikke tilgang til serveren for øyeblikket. Prøv igjen senere." });
	}
}
</script>