<template>
	<div class="container">
		<h1 class="text-center">KART</h1>
		<div id="map" style="width: 100%; height: calc(100vh - 250px);"></div>
	</div>
</template>
<script lang="ts" setup>
import * as atlas from "azure-maps-control";
import { onMounted, onUnmounted } from "vue";
import { SecureApiClient } from "../autogeneratedServices";

let _map: atlas.Map | null = null;

onMounted(async () => {
	await initMap();
});

onUnmounted(() => {
	if (_map) {
		_map.dispose();
	}
});

async function initMap() {
	let azureMapsKey = "";
	try {
		const api = new SecureApiClient("");
		azureMapsKey = await api.getAzureMapsKey();
	}
	catch (err) {
		alert("En feil har oppstått. Vennligst prøv igjen senere.");
		return;
	}

	// eslint-disable-next-line no-undef
	const myPosition: GeolocationPosition | null = await new Promise((resolve) => {
		if (!navigator.geolocation) {
			resolve(null);
			return;
		}
		navigator.geolocation.getCurrentPosition((myPosition) => {
			resolve(myPosition);
		});
	});

	if (!myPosition) {
		alert("Kunne ikke finne din posisjon.");
	}

	const map = _map ?? new atlas.Map("map", {
		view: "Auto",
		center: myPosition ? [myPosition.coords.longitude, myPosition.coords.latitude] : [0, 0],
		zoom: 12,
		authOptions: {
			authType: atlas.AuthenticationType.subscriptionKey,
			subscriptionKey: azureMapsKey,
		},
	});
	_map = map;

	if (!myPosition) {
		return;
	}

	//Wait until the map resources are ready.
	map.events.add("ready", function () {

		map.controls.add(new atlas.control.ZoomControl(), {
			position: atlas.ControlPosition.TopRight
		});

		const source = new atlas.source.DataSource();
		map.sources.add(source);

		const myPositionFeature = new atlas.data.Feature(new atlas.data.Point([myPosition!.coords.longitude, myPosition!.coords.latitude]), {
			name: "Din posisjon",
			description: "Du er her!"
		});

		const futuraPositionFeature = new atlas.data.Feature(new atlas.data.Point([7.7785893, 63.1104077]), {
			name: "Nærmeste offentlige bomberom",
			description: "Futura, Industriveien 17, 6517 Kristiansund"
		});

		source.add([myPositionFeature, futuraPositionFeature]);

		const symbolLayer = new atlas.layer.SymbolLayer(source, undefined, {
			iconOptions: {
				image: "pin-round-darkblue",
				anchor: "center",
				allowOverlap: true
			}
		});
		map.layers.add(symbolLayer);

		const popupTemplate = '<div style="padding: 5px; font-size: 1rem;"><strong>{name}</strong><br/>{description}</div>';

		const myPositionPopup = new atlas.Popup({
			pixelOffset: [0, -18],
			closeButton: false
		});

		const bounds = atlas.data.BoundingBox.fromPositions([myPositionFeature.geometry.coordinates, futuraPositionFeature.geometry.coordinates]);
		map.setCamera({
			bounds: bounds,
			padding: 100
		});

		map.events.add("mouseover", symbolLayer, function (e) {
			if (e.shapes && e.shapes.length > 0) {
				// @ts-ignore
				const properties = e.shapes[0].getProperties();
				const content = popupTemplate.replace(/{name}/g, properties.name).replace(/{description}/g, properties.description);
				// @ts-ignore
				const coordinate = e.shapes[0].getCoordinates();

				myPositionPopup.setOptions({
					content: content,
					position: coordinate
				});

				myPositionPopup.open(map);
			}
		});

		map.events.add("mouseleave", symbolLayer, function () {
			myPositionPopup.close();
		});
	});
}
</script>