<template>
	<div>
		<div class="container text-center">
			<h2>{{ myHome?.name?.toUpperCase() ?? "MITT HJEM" }}</h2>
		</div>
		<div v-if="!isLoading" class="mb-5">
			<a href="#" v-if="!myHome" @click.prevent="addHome()">Legg til nytt hjem</a>
			<div v-if="myHome">
				<div v-for="itemType in itemTypes" :key="itemType.id">
					<div class="accordion" id="accordionExample">
						<div class="accordion-item my-4 border rounded">
							<div class="accordion-header" :id="'heading' + itemType.id">
								<button class="accordion-button fs-4 collapsed" type="button" data-bs-toggle="collapse" :data-bs-target="'#collapse' + itemType.id" :aria-controls="'collapse' + itemType.id">
									<div class="d-flex">
										<img :src="'../../images/BeredskapspakkeImg/'+ itemType.id+'.jpeg'" :alt="itemType.name" style="height: 100px; width: 100px;"> 
										<div class="my-auto ms-3">
											<h3 class="text-break">{{ itemType.name }}</h3>
											<p class="">{{ getNumberOfUnits(itemType.id ?? 0) }} / {{ getRecomendedAmount(itemType) }} {{ itemType.unit }}</p>
										</div>
									</div>
								</button>
							</div>
							<div :id="'collapse' + itemType.id" class="accordion-collapse collapse bg-light" :aria-labelledby="'heading' + itemType.id" data-bs-parent="#accordionExample">
								<div class="accordion-body p-3">
									<div v-for="item in myHome.items?.filter(e => e.itemTypeId == itemType.id)" :key="item.id">
										<div v-if="item.id !== 0" class="d-flex border rounded w-100 p-2 mb-3 bg-white">
											<span class="my-auto">{{ item.numberOfUnits + " " + itemType.unit }} {{ item.sellByDate ? "- Utløpsdato" + moment(item.sellByDate).utc(true).local().format("DD.MM.YYYY") : "" }}</span>
											<button type="button" class="btn btn-danger ms-auto" @click="removeItem(item.id!)" aria-label="Slett">
												<i class="fa-solid fa-trash"></i>
											</button>
										</div>
									</div>
									<button type="button" class="btn btn-primary ms-auto" @click="addItem(itemType.id!)">
										<i class="fa-solid fa-plus"></i> Legg til
									</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>

<script lang="ts" setup>
import { ref, onMounted } from "vue";
import { HomeEntity, ItemEntity, ItemTypeEntity, SecureApiClient } from "../autogeneratedServices";
import moment from "moment";

const api = new SecureApiClient("");
const myHome = ref<HomeEntity | null>(null);
const itemTypes = ref<ItemTypeEntity[]>([]);
const isLoading = ref(true);

onMounted(async () => {
	myHome.value = await api.getHome();
	itemTypes.value = await api.getItemTypes();
	isLoading.value = false;
});

async function refetch() {
	if (!myHome.value) {
		console.error("No home!");
		return;
	}
	const items = await api.getItems(myHome.value?.id);
	myHome.value.items = items;
}

async function addHome() {
	const n = prompt("Hvor mange bor i boligen?");
	await api.addHome(Number(n));
	myHome.value = await api.getHome();
}

function getNumberOfUnits(itemTypeId: number) {
	const items = myHome.value?.items?.filter(e => e.itemTypeId === itemTypeId);
	if (!items) {
		return 0;
	}

	let count = 0;
	items.forEach(item => {
		count += item.numberOfUnits ?? 1;
	});

	return count;
}

function getRecomendedAmount(itemType?: ItemTypeEntity) {
	if (!itemType) {
		return 0;
	}
	if (itemType.excludeFromTotal) {
		return itemType.recomendedUnitPerPerson;
	}

	return itemType.recomendedUnitPerPerson! * myHome.value!.numberOfInhabitants!;
}

async function addItem(itemTypeId: number) {
	const n = prompt("Hvor mange vil du legge til med samme utløpsdato?");
	const date = prompt("Valgfritt legg in utløpsdato (YYYY.MM.DD):");

	const item = new ItemEntity({
		itemTypeId: itemTypeId,
		homeId: myHome.value?.id,
		numberOfUnits: 1
	});

	const numberOfUnits = Number(n);
	if (numberOfUnits > 0) {
		item.numberOfUnits = numberOfUnits;
	}

	if (date !== "") {
		const dateDate = moment(date).toDate();
		dateDate.setHours(5);
		item.sellByDate = dateDate;
	}

	await api.addItem(item);
	refetch();
}

async function removeItem(id:number) {
	await api.removeItem(id);
	refetch();
}

</script>