

using Core;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using NSwag;
using NSwag.CodeGeneration.TypeScript;
using oledid.SyntaxImprovement;
using Web.Code;

namespace Web.Controllers
{
	[ApiController]
	[ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
	[Route("/Secure/[controller]/[action]")]
	public class ActionsController : ControllerBase
	{
		private readonly IConfiguration configuration;

		public ActionsController(IConfiguration configuration)
		{
			this.configuration = configuration;
		}

		public async Task<IActionResult> ThrowError()
		{
			throw new Exception("Dette er en test-feilmelding");
		}

		public async Task<IActionResult> GenerateTsFromSwagger()
		{
			if (HttpContext.Request.GetDisplayUrl().ToLowerInvariant().StartsWith("https://local.paakobla.no") == false)
			{
				throw new NotSupportedException();
			}

			var urlHelper = new UrlHelper(configuration);
			var document = await OpenApiDocument.FromUrlAsync(urlHelper.ResolveUrl("~/swagger/v1/swagger.json"));

			var settings = new TypeScriptClientGeneratorSettings
			{
				ClassName = "{controller}Client"
			};

			var generator = new BugfixedTypeScriptClientGenerator(document, settings);
			var code = generator.GenerateFile();

			var path = Path.GetFullPath(Path.Join(CompilerInformation.GetCallerSourceFilePath(), "../../wwwroot/scripts/autogeneratedServices.ts"));
			var file = new FileInfo(path);
			Console.WriteLine("Writing TS interfaces to: " + file.FullName);
			await System.IO.File.WriteAllTextAsync(file.FullName, "// Autogenerated on build - do not edit\r\n\r\n" + code);

			return Content("OK", "text/plain");
		}

		public async Task<IActionResult> SetStatusToNormal()
		{
			return Content("OK", "text/plain");
		}

		public async Task<IActionResult> SetStatusToWarning()
		{
			return Content("OK", "text/plain");
		}

		public async Task<IActionResult> SetStatusToDanger()
		{
			return Content("OK", "text/plain");
		}

	}
}
